"""add updated_at to projects

Revision ID: a5fc1c66dc24
Revises: 67b93d03a8b8
Create Date: 2026-06-26 02:00:40.123811
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a5fc1c66dc24'
down_revision: Union[str, None] = '67b93d03a8b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'updated_at')
    # ### end Alembic commands ###
